# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a43c497974b597addc2579f75586c0208eba4343324a9d93d397c81dabfd8d7dac8e42e124c36f2fc057cdc46d18612b9840648bdef43faa1423927e89f015b

test:
  secret_key_base: 4b9fb47d722805f87009e259e357df9c7a4bd24b894d75ed64779612c0df4fad580d03152ff9a05cb53baaacfc6e1e8448a07589fc29bb5c7b0fd5b55ec4dc84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
